apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: mi-aplicacion
        image: jfmarquez23/python_devops:latest
        ports:
        - containerPort: 8000