name: CI/CD Pipeline

on:
  push:
    branches:
      - master  #Nombre de la rama
  pull_request:
    branches:
      - master

jobs:
  build-test-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    #CodeBuild
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #Test
    - name: Ejecutar tests
      run: |
        python manage.py test

    # Code Coverage
    - name: Check code coverage
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
  
  #Construir Imagen y Subirla en DockerHub
  docker-build-push:
    needs: build-test-analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD  }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/python_devops:latest  # Nombre de la imagen

    # Escaneo Vulnerabilidades imagen
    - name: Scan the Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'jfmarquez23/python_devops:latest'
        format: 'table'